[package]
name = "fontsdf"
version = "0.4.0"
edition = "2021"
description = "fontdue extension to generate sdf:s directly"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttf-parser = "0.15"
ordered-float = "3.0"
glam = "0.20"
fontdue = "0.7"

[dev-dependencies]
image = "0.24"
